const list = [
    {
      id: 1,
      title: "Regular Fit Blue Chair",
      price: 48.40,
      img: "/sh1.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Couch Sofa",
      price: 230.78,
      img: "/sh2.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh3.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh4.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh5.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh6.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh7.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh8.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh9.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh10.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh11.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh12.jpg",
      amount: 1,
    },
    {
      id: 13,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh13.jpg",
      amount: 1,
    },
    {
      id: 14,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh14.jpg",
      amount: 1,
    },
    {
      id: 15,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh15.jpg",
      amount: 1,
    },
    {
      id: 16,
      title: "Regular Fit V-Neck Sweater",
      price: 4900.00,
      img: "/sh16.jpg",
      amount: 1,
    },
  ];
  
  export default list;