import Head from 'next/head'
import Header from './component/Header'
import Footer from './component/Footer'
import styles from '../styles/Home.module.css'
// import Cart from "./component/cart";
import React, { useState, useEffect } from "react";



export default function Home() {
    const [show, setShow] = useState(true);
  const [cart, setCart] = useState([]);

  const handleClick = (item) => {
    if (cart.indexOf(item) !== -1) return;
    setCart([...cart, item]);
  };

  const handleChange = (item, d) => {
    const ind = cart.indexOf(item);
    const arr = cart;
    arr[ind].amount += d;

    if (arr[ind].amount === 0) arr[ind].amount = 1;
    setCart([...arr]);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>`Marvric` Furniture & More</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.3.1/default/snipcart.css" />
        </Head>
        <body>
          <script async src="https://cdn.snipcart.com/themes/v3.3.1/default/snipcart.js"></script>
          <div hidden id="snipcart" data-api-key="YzFkOTM2OTktNzM4NS00YzM5LWEwZTktOTM5Mjc5ZmZjYWI1NjM3OTA0NzQ3MTE5MjI2OTU3"></div>
          <Header />
          {/* {show ? <Furniture handleClick={handleClick} />:<Cart cart={cart} setCart={setCart} handleChange={handleChange} />} */}
          <Footer />
        </body>
        
    </div>
  )
}
