import Head from 'next/head'
import Header from './component/Header'
import Footer from './component/Footer'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marvric Furniture & More</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <Footer />
    </div>
  )
}
